spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:127.0.0.1}:${DB_PORT:3306}/${DB_SCHEMA:demo}?useUnicode=true&allowPublicKeyRetrieval=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: ${DB_USERNAME:admin}
    password: ${DB_PASSWORD:password}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 100
      minimum-idle: 10
      connection-timeout: 40000
      idle-timeout: 60000
      max-lifetime: 2400000
      connection-init-sql: SET NAMES 'utf8mb4'
  data:
    redis:
      connect-timeout: 300
      host: ${REDIS_HOST:127.0.0.1}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:password}
      cache-prefix: ${REDIS_CACHE_PREFIX:inferium}
      client-type: lettuce
      lettuce:
        pool:
          maxActive: ${REDIS_POOL_ACTIVE:40}
          maxIdle: ${REDIS_POOL_MAX_IDLE:40}
          minIdle: ${REDIS_POOL_MIN_IDLE:4}
  jpa:
#    hibernate:
#      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
  rabbitmq:
    host: ${RABBIT_MQ_HOST:localhost}
    port: ${RABBIT_MQ_PORT:5672}
    username: ${RABBIT_MQ_USERNAME:guest}
    password: ${RABBIT_MQ_PASSWORD:guest}

## Debug SQL
#  jpa:
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true

logging:
  level:
    root: INFO